services:
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env  # Chỉ định file .env
