name: NestJS API CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # <database-relational-block>
      - name: Run e2e tests for NestJS with TypeORM
        id: relational
        run: docker compose -f docker-compose.relational.ci.yaml --env-file env-example-relational -p ci-relational up --build --exit-code-from api

      # - name: Copy prod.log from container to host
      #   run: docker cp ci-relational-api-1:/usr/src/app/prod.log .
      # </database-relational-block>

      - name: Upload prod.log to artifacts for debugging
        uses: actions/upload-artifact@v4
        with:
          name: prod-logs
          path: prod.log
