name: NestJS API CI

on:
  push:
    branches: [feat/product_cicd]
  pull_request:
    branches: [feat/product_cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'executing remote ssh commands using password'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          echo $SSH_PRIVATE_KEY > ~/.ssh/hulibservice_rsa
          chmod 600 ~/.ssh/hulibservice_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/hulibservice_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          chmod +x auto_ssh.sh
          ./auto_ssh.sh -i ~/.ssh/hulibservice_rsa -p $PASSPHRASE -u vodacluc -h $HOST -c "./deploy.sh"
