name: NestJS Production API CI

on:
  push:
    branches: [feat/product_cicd]
  pull_request:
    branches: [feat/product_cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Run building test for NestJS with TypeORM'
        id: relational
        run: |
          docker compose -f docker-compose.prod.yaml up --build --exit-code-from api
      
      - name: Copy prod.log from container to host
        if: ${{ failure() && steps.relational.conclusion == 'failure' }}
        run: docker cp ci-relational-api-1:/usr/src/app/prod.log .
      # </database-relational-block>

      - name: 'Executing remote ssh and deploy script'
        if: ${{ failure() && steps.relational.conclusion == 'failure' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: vodacluc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            chmod +x deploy.sh
            ./deploy.sh