name: NestJS Production API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      
      - name: 'Healthcheck database'
        run: |
          psql "${{ secrets.DATABASE_URL }}" -c "SELECT 1;"

      # - name: 'Run building test for NestJS with TypeORM'
      #   id: relational
      #   run: |
      #     docker compose -f docker-compose.prod.yaml up --build --exit-code-from api
      
      # - name: Copy prod.log from container to host
      #   run: docker cp ci-relational-api-1:/usr/src/app/prod.log .
      # </database-relational-block>

      # - name: 'Executing remote ssh and deploy script'
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: vodacluc
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     port: 22
      #     script: |
      #       chmod +x deploy.sh
      #       ./deploy.sh