name: NestJS Production API CI

on:
  push:
    branches: [feat/product_cicd]
  pull_request:
    branches: [feat/product_cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Run building test for NestJS with TypeORM'
        run: |
          ./deploy.sh

      - name: 'Executing remote ssh and deploy script'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: vodacluc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            chmod +x deploy.sh
            ./deploy.sh